-- Script de inicialização do banco de dados
-- Execute este script no seu PostgreSQL

-- Criar banco de dados (opcional)
-- CREATE DATABASE usuarios_db;

-- Conectar ao banco
-- \c usuarios_db;

-- Criar tabela de usuários
DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  pronome TEXT,
  senha TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  telefone TEXT,
  data_nascimento DATE,
  cpf TEXT UNIQUE,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  deleteAt TIMESTAMP WITH TIME ZONE,
  deleteBy BIGINT
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_usuario_email ON usuario(email);
CREATE INDEX IF NOT EXISTS idx_usuario_cpf ON usuario(cpf);
CREATE INDEX IF NOT EXISTS idx_usuario_active ON usuario(active);
CREATE INDEX IF NOT EXISTS idx_usuario_timestamp ON usuario(timestamp);

-- Comentários para documentação
COMMENT ON TABLE usuario IS 'Tabela de usuários do sistema';
COMMENT ON COLUMN usuario.id IS 'Identificador único do usuário';
COMMENT ON COLUMN usuario.nome IS 'Nome completo do usuário';
COMMENT ON COLUMN usuario.pronome IS 'Pronome de tratamento do usuário';
COMMENT ON COLUMN usuario.senha IS 'Hash da senha do usuário';
COMMENT ON COLUMN usuario.email IS 'Email único do usuário';
COMMENT ON COLUMN usuario.telefone IS 'Número de telefone do usuário';
COMMENT ON COLUMN usuario.data_nascimento IS 'Data de nascimento do usuário';
COMMENT ON COLUMN usuario.cpf IS 'CPF único do usuário';
COMMENT ON COLUMN usuario.timestamp IS 'Data e hora de criação do registro';
COMMENT ON COLUMN usuario.active IS 'Status ativo/inativo do usuário';
COMMENT ON COLUMN usuario.deleteAt IS 'Data e hora da exclusão (soft delete)';
COMMENT ON COLUMN usuario.deleteBy IS 'ID do usuário que realizou a exclusão';

-- Inserir usuário administrador padrão (opcional)
-- Senha: Admin123! (hash: $2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/4KzqK2K)
INSERT INTO usuario (nome, email, senha, active) 
VALUES ('Administrador', 'admin@exemplo.com', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/4KzqK2K', true)
ON CONFLICT (email) DO NOTHING;

-- Verificar se a tabela foi criada corretamente
SELECT 
  column_name, 
  data_type, 
  is_nullable, 
  column_default
FROM information_schema.columns 
WHERE table_name = 'usuario' 
ORDER BY ordinal_position;
